spring:
  thymeleaf:
    enabled: true
    cache: true
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true

  message:
    basename: /message/errorMsg
    encoding: UTF-8
    always-use-message-format: true
    use-code-as-default-message: true
    fallback-to-system-locale: true
    mvc:
      throw-exception-if-no-handler-found: true

server:
  port: 32000
  servlet:
    context-path:
    encoding:
      charset: UTF-8

mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

---
spring:
  config:
    activate:
      on-profile: "local"

  datasource:
    #jndi-name: jndi/mariadb
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://dudqls3kr.cafe24.com:3306/dudqls3kr?useUnicode=true&characterEncoding=utf8
    username: dudqls3kr
    password: dkapflRksh1!
    jmx-enable: false

  data:
    redis:
      port: 6379
      host: 127.0.0.1
      password: admin

  graphql:
    websocket:
      path: 192.168.202.13:32000

  file:
    profile-path: file:///D:/zeroBin/profile/
    profile-upload-path: D:/zeroBin/profile/


---
spring:
  config:
    activate:
      on-profile: "prod"

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://dudqls3kr.cafe24.com:3306/dudqls3kr?useUnicode=true&characterEncoding=utf8
    username: dudqls3kr
    password: dkapflRksh1!
    jmx-enable: false

  data:
    redis:
      port: 22529
      host: dudqls4kr.cafe24.com
      password:

  graphql:
    websocket:
      path: 210.114.6.196:8831

  file:
    profile-path: /dudqls3kr/image/profile/
    profile-upload-path: /dudqls3kr/image/profile/
