spring:
  message:
    basename: /message/errorMsg
    encoding: UTF-8
    always-use-message-format: true
    use-code-as-default-message: true
    fallback-to-system-locale: true
    mvc:
      throw-exception-if-no-handler-found: true

server:
  port: 32000
  servlet:
    context-path:
    encoding:
      charset: UTF-8

mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

---
spring:
  config:
    activate:
      on-profile: "local"

  datasource:
    #jndi-name: jndi/mariadb
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://192.168.202.13:3306/MYMSG?useUnicode=true&characterEncoding=utf8
    username: ${MARIA_DB_USER}
    password: ${MARIA_DB_PASS}
    jmx-enable: false

  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: 192.168.202.13
    password: admin

  file:
    base-path: "D:\\cyb\\images\\profile\\"